### ISSUE TITLE
ICS class declaration is missing

### ISSUE THREAD

**Issue by jstask82** [wpmetabox/docsv2#25]
An important part of the event guide is missing. Wehre can i get the ICS class declaration in https://github.com/wpmetabox/docsv2/blob/4aed8edd909028e9656b497014a2f7f9ca915db9/docs/tutorials/create-add-to-calendar-buttons.md

**Comment by rilwis** [comment]
Hi @jstask82 

We've updated the docs with the link to the file: https://github.com/wpmetabox/tutorials/blob/master/ics-calendar/ICS.php
